import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/base.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="fixed top-0 w-full left-0 py-3 px-2">
					<div className="wrapper flex gap-4 justify-end font-workSans font-light text-white">
						<Link className="shrink-0 button--yellow" href="/dashboard">
							Dashboard
						</Link>
						<Link className="shrink-0 button--yellow" href="/scheduled">
							View All Messages
						</Link>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
